# Generated by Django 3.2 on 2021-05-09 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название')),
                ('Phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Note', models.TextField(blank=True, verbose_name='Примечание')),
                ('DateDel', models.DateField(verbose_name='Дата удаления')),
                ('ContactFIO', models.TextField(blank=True, verbose_name='Контактное лицо')),
                ('ContactPhone', models.TextField(max_length=12, verbose_name='Телефон')),
                ('ContactEmail', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Имя')),
                ('Fname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('Date', models.DateField(verbose_name='Дата рождения')),
                ('Phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Passport', models.CharField(max_length=50, verbose_name='Паспорт')),
                ('Position', models.IntegerField(blank=True, verbose_name='Позиция')),
                ('Comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('NumVU', models.CharField(max_length=50, verbose_name='Номер ВУ')),
                ('Password', models.CharField(blank=True, max_length=150, verbose_name='Пароль')),
                ('DateDel', models.DateField(verbose_name='Дата удаления')),
                ('Company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='user_and_company.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
