# Generated by Django 3.2 on 2021-05-09 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user_and_company.company', verbose_name='Компания'),
        ),
    ]
