# Generated by Django 3.2 on 2021-05-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_company', '0002_alter_person_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ContactFIO',
            field=models.CharField(blank=True, max_length=150, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ContactPhone',
            field=models.CharField(max_length=12, verbose_name='Телефон'),
        ),
    ]
