# Generated by Django 3.2 on 2021-06-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_company', '0003_auto_20210509_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='person',
            name='DateDel',
            field=models.DateField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='person',
            name='NumVU',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер ВУ'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Password',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Position',
            field=models.IntegerField(blank=True, choices=[(0, 'Администратор'), (1, 'Сотрудник'), (2, 'Клиент')], default=0, null=True, verbose_name='Позиция'),
        ),
    ]
