# Generated by Django 3.2 on 2021-06-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_company', '0004_auto_20210608_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Passport',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Паспорт'),
        ),
    ]
