# Generated by Django 3.2 on 2021-06-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_company', '0005_auto_20210608_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='DateDel',
            field=models.DateField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='company',
            name='Note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
    ]
