# Generated by Django 3.2 on 2021-06-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_company', '0006_auto_20210608_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='workers',
            field=models.ManyToManyField(to='user_and_company.Person'),
        ),
    ]
