# Generated by Django 3.2 on 2021-06-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_company', '0007_company_workers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='workers',
        ),
        migrations.AddField(
            model_name='person',
            name='cats',
            field=models.JSONField(default={}, verbose_name='Категории'),
            preserve_default=False,
        ),
    ]
