# Generated by Django 3.2 on 2021-06-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_company', '0008_auto_20210609_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='cats',
        ),
        migrations.AddField(
            model_name='person',
            name='CategoryVU',
            field=models.JSONField(blank=True, null=True, verbose_name='Категории'),
        ),
    ]
