# Generated by Django 3.2 on 2021-06-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_company', '0009_auto_20210610_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='CategoryVU',
            field=models.JSONField(blank=True, default='{}', null=True, verbose_name='Категории'),
        ),
    ]
