# Generated by Django 3.2 on 2021-05-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientID', models.IntegerField(verbose_name='ID Клиента')),
                ('Review', models.TextField(verbose_name='Текст отзыва')),
                ('Photo', models.CharField(max_length=250, verbose_name='Фото')),
                ('Status', models.BooleanField(verbose_name='Статус')),
                ('Date', models.DateField(verbose_name='Дата отзыва')),
                ('DateDel', models.DateField(verbose_name='Дата удаления')),
            ],
        ),
    ]
