# Generated by Django 3.2 on 2021-05-09 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_company', '0002_alter_person_company'),
        ('reviews', '0003_alter_reviews_clientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='ClientID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user_and_company.person', verbose_name='ID клиента'),
        ),
    ]
