# Generated by Django 3.2 on 2021-05-07 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='CategoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.category'),
        ),
    ]
