# Generated by Django 3.2 on 2021-05-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Icon',
            field=models.ImageField(upload_to='img_category/', verbose_name='Путь до иконки'),
        ),
    ]
