# Generated by Django 3.2 on 2021-05-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Location',
            field=models.CharField(max_length=250, null=True, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Icon',
            field=models.ImageField(upload_to='img_category', verbose_name='Путь до иконки'),
        ),
    ]
