# Generated by Django 3.2 on 2021-05-09 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_company', '0001_initial'),
        ('cars', '0007_auto_20210509_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='CategoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='car',
            name='CompanyID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='user_and_company.company', verbose_name='ID Компании'),
        ),
    ]
