# Generated by Django 3.2 on 2021-05-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20210509_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='CategoryVUID',
            field=models.IntegerField(blank=True, null=True, verbose_name='Категория ВУ'),
        ),
    ]
