# Generated by Django 3.2 on 2021-06-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_categoryvuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Photo',
            field=models.JSONField(verbose_name='Фото'),
        ),
    ]
