# Generated by Django 3.2 on 2021-06-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Photo',
            field=models.JSONField(null=True, verbose_name='Фото'),
        ),
    ]
