# Generated by Django 3.2 on 2021-06-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_alter_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='wheel_drive',
            field=models.IntegerField(blank=True, null=True, verbose_name='Руль'),
        ),
        migrations.AlterField(
            model_name='car',
            name='Brand_and_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Марка и модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='DateDel',
            field=models.DateField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='car',
            name='Driver',
            field=models.BooleanField(blank=True, null=True, verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='FixedRate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Фиксированная ставка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='Header',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='car',
            name='Location',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='car',
            name='Percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Комиссия'),
        ),
        migrations.AlterField(
            model_name='car',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='img_cars', verbose_name='Фото ТС'),
        ),
        migrations.AlterField(
            model_name='car',
            name='RentCondition',
            field=models.TextField(blank=True, null=True, verbose_name='Условия аренды'),
        ),
        migrations.AlterField(
            model_name='car',
            name='Status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кузов'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.IntegerField(blank=True, null=True, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.IntegerField(blank=True, null=True, verbose_name='Двигатель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='power',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мощность'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.IntegerField(blank=True, null=True, verbose_name='Коробка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год'),
        ),
    ]
