# Generated by Django 3.2 on 2021-06-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_auto_20210610_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Седан'), (1, 'Кроссовер'), (2, 'Универсал'), (3, 'Хэтчбек'), (4, 'Купе'), (5, 'Микро')], default=0, null=True, verbose_name='Кузов'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.IntegerField(blank=True, choices=[(0, 'Полный'), (1, 'Задний'), (2, 'Передний')], default=0, null=True, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.IntegerField(blank=True, choices=[(0, 'Бензиновый'), (1, 'Дизельный')], default=0, null=True, verbose_name='Двигатель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.IntegerField(blank=True, choices=[(0, 'Механическая'), (1, 'Автоматическая')], default=0, null=True, verbose_name='Коробка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='wheel_drive',
            field=models.IntegerField(blank=True, choices=[(0, 'Правый'), (1, 'Левый')], default=0, null=True, verbose_name='Руль'),
        ),
    ]
