# Generated by Django 3.2 on 2021-06-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_auto_20210611_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img_cars', verbose_name='Фото ТС'),
        ),
    ]
