# Generated by Django 3.2 on 2021-06-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0022_remove_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img_cars', verbose_name='Фото ТС'),
        ),
        migrations.AddField(
            model_name='car',
            name='Photos',
            field=models.JSONField(default='{}', verbose_name=''),
        ),
    ]
