# Generated by Django 3.2 on 2021-06-12 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_and_company', '0012_auto_20210610_2044'),
        ('cars', '0022_remove_car_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateStartContract', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('DateEndContract', models.DateField(blank=True, null=True, verbose_name='Дата нокончания')),
                ('Driver', models.BooleanField(blank=True, null=True, verbose_name='Нужен ли водитель')),
                ('Note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('Status', models.BooleanField(blank=True, null=True, verbose_name='Статус заказа')),
                ('Comission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Комиссия')),
                ('Cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Стоимость')),
                ('DateDel', models.DateField(blank=True, null=True, verbose_name='Дата удаления')),
                ('Car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.car', verbose_name='Авто')),
                ('Client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user_and_company.person', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
