# Generated by Django 3.2 on 2021-06-13 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_contract_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfPayment', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('AmmountPaid', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Сумма платежа')),
                ('Contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.contract', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
