# Generated by Django 3.2 on 2021-06-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='AmmountPaid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма платежа'),
        ),
    ]
