# Generated by Django 3.2 on 2021-06-13 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_company', '0012_auto_20210610_2044'),
        ('orders', '0005_alter_payment_ammountpaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('Date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('Status', models.BooleanField(blank=True, null=True, verbose_name='Статус')),
                ('Contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.contract', verbose_name='Заказ')),
                ('From', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user_and_company.person', verbose_name='Отправитель')),
            ],
        ),
    ]
