# Generated by Django 3.2 on 2021-06-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210613_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='DateEndContract',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
