# Generated by Django 3.2 on 2021-06-18 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0024_remove_car_photo'),
        ('orders', '0008_alter_contract_dateendcontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='Car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='car', to='cars.car', verbose_name='Авто'),
        ),
    ]
