# Generated by Django 3.2 on 2021-06-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_contract_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-id'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='Comission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Комиссия'),
        ),
    ]
