# Generated by Django 3.2 on 2021-06-16 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_and_company', '0012_auto_20210610_2044'),
        ('orders', '0008_alter_contract_dateendcontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackAndComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('Status', models.BooleanField(blank=True, null=True, verbose_name='Статус сообщения обратной связи')),
                ('Type', models.BooleanField(blank=True, null=True, verbose_name='Тип сообщения')),
                ('Phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('DateDel', models.DateField(blank=True, null=True, verbose_name='Дата удаления')),
                ('Client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user_and_company.person', verbose_name='Клиент')),
                ('Contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.contract', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Комментарий или сообщение',
                'verbose_name_plural': 'Комментарии или сообщения',
            },
        ),
    ]
