# Generated by Django 3.2 on 2021-06-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_and_comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackandcomment',
            name='Date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
