# Generated by Django 3.2 on 2021-06-16 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_company', '0012_auto_20210610_2044'),
        ('feedback_and_comments', '0002_feedbackandcomment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackandcomment',
            name='Client',
        ),
        migrations.AddField(
            model_name='feedbackandcomment',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user_and_company.person', verbose_name='Админ или сотрудник'),
        ),
    ]
