# Generated by Django 3.2 on 2021-06-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_and_comments', '0003_auto_20210616_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackandcomment',
            name='Name',
            field=models.CharField(default='', max_length=50, verbose_name='Имя'),
        ),
    ]
