# Generated by Django 3.2 on 2021-06-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_and_comments', '0004_feedbackandcomment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackandcomment',
            name='Phone',
        ),
        migrations.AddField(
            model_name='feedbackandcomment',
            name='PhoneEmail',
            field=models.CharField(default='', max_length=12, verbose_name='Телефон или почта'),
        ),
    ]
