# Generated by Django 3.2 on 2021-06-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_and_comments', '0005_auto_20210616_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackandcomment',
            options={'ordering': ['-id'], 'verbose_name': 'Комментарий или сообщение', 'verbose_name_plural': 'Комментарии или сообщения'},
        ),
    ]
